name       : gwenview
version    : 17.08.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/gwenview-17.08.1.tar.xz : 678f0696c12f154a0ac84678a8948d5f66a4ead40cf50c701c1eeb03003aacb8
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
summary    : Fast and easy to use image viewer by KDE
description: |
    Gwenview is able to load and save to a variety of image formats supported by KDE applications, such as PNG, JPEG, and even the Gimp's XCF! Gwenview also sports a beautiful thumbnail toolbar when viewing images in fullscreen. Gwenview's simple interface doesn't get in the way and lets you view your images quickly and easily.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gl)
    - pkgconfig(lcms2)
    - pkgconfig(libKActivities)
    - pkgconfig(libpng)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - baloo-devel
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - knotifications-devel
    - kparts-devel
    - kwindowsystem-devel
    - libjpeg-turbo-devel
    - libkdcraw-devel
    - libkipi-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
