name       : gwenview
version    : 22.04.1
release    : 70
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/gwenview-22.04.1.tar.xz : f99a8f6eb7c7e2ba8b3f434512a2050cf64e032c48830c3ad80dbbb6d5e9cc4a
homepage   : https://kde.org/applications/graphics/org.kde.gwenview
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : Fast and easy to use image viewer by KDE
description: |
    Gwenview is able to load and save to a variety of image formats supported by KDE applications, such as PNG, JPEG, and even the Gimp's XCF! Gwenview also sports a beautiful thumbnail toolbar when viewing images in fullscreen. Gwenview's simple interface doesn't get in the way and lets you view your images quickly and easily.
optimize   : lto
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(exiv2)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(phonon4qt5)
    - pkgconfig(x11)
    - kactivities-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knotifications-devel
    - kparts-devel
    - libkdcraw-devel
    - purpose-devel
rundeps    :
    - kimageformats
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove doc
    rm -rf $installdir/usr/share/doc
